version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 20

    commands:
      - npm install

  pre_build:
    commands:
      - npm run test:all
      - npm run check-formatting
      - npm run check-duplicates

  build:
    commands:
      - npm run build:prod

artifacts:
  files:
    - "**/*"
  exclude-paths:
    - src/**/*
  base-directory: "dist"

cache:
  paths:
    - "node_modules/**/*"
