AWSTemplateFormatVersion: '2010-09-09'
Resources:
  IsUploadFlagSwitch:
    Type: 'AWS::Lambda::Function'
    Properties:
      FunctionName: IsUploadFlagSwitch
      Handler: index.handler
      Role: arn:aws:iam::381491932671:role/service-role/s3-read-file-permission
      Code:
        S3Bucket: ml-images-processor-server
        S3Key: functions/is-uploaded-flag-switch.zip
      Runtime: node20
      Timeout: 10
      MemorySize: 128