version: "1.0"

services:
  db:
    image: postgres
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5432:5432"
  server:
    build: .
    restart: always
    volumes:
      - ./data/db:/var/lib/server/data
    develop:
      watch:
        - action: rebuild
          path: package.json
      ports:
        - "8000:8000"
    depends_on:
      - db
